# Site settings
baseURL = "/"
languageCode = "en-GB"
title = "Phil Mike Jones"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-44027458-2"

# Copyright
copyright = "&copy;2012-2018 Phil Mike Jones"

[params]

  # Metadata for search engines and social sharing
  author = "Phil Mike Jones"
  description = "Blog posts on R, geography, GIS, mapping, cartography, and occasionally photography."
  shareImage = "images/social.jpg"
  twitterHandle = "philmikejones"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpeg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links

  [[params.links]]
    [params.links.list1]
      heading = "Code"

      [[params.links.list1.link]]
        text = "Github"
        url = "https://github.com/philmikejones"

      [[params.links.list1.link]]
        text = "Stack Exchange"
        url = "https://stackexchange.com/users/3624034"


  [[params.links]]
    [params.links.list2]
      heading = "Academic"

      [[params.links.list2.link]]
        text = "ORCID"
        url = "https://orcid.org/0000-0001-5173-3245"


  [[params.links]]
    [params.links.list3]
      heading = "Photography"

      [[params.links.list3.link]]
        text = "Flickr"
        url = "https://www.flickr.com/people/phil-jones/"


  [[params.links]]
    [params.links.list4]
      heading = "Social"

      [[params.links.list4.link]]
          text = "Twitter"
          url = "https://twitter.com/philmikejones"

# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution, you can check out
# the license option via the template author's website: https://onepagelove.com/split
